export const artisanSeed = {
  id: "rajesh-001",
  phone: "9876543210",
  name: "राजेश कुमार",
  slug: "rajesh-kumar",
  language: "hi",
  craft: "terracotta + handloom",
  district: "Bhopal",
  state: "Madhya Pradesh",
  gstMode: "NONE",
  dayWage: 500,
};

export const productsSeed = [
  {
    id: "tp-lamp-001",
    artisanId: "rajesh-001",
    slug: "terracotta-lamp",
    titleEn: "Terracotta Lamp",
    titleHi: "मिट्टी का दीपक",
    descriptionEn: "Handcrafted terracotta lamp with traditional design",
    descriptionHi: "परम्परागत डिजाइन के साथ हाथ से बनाया गया मिट्टी का दीपक",
    keywords: ["terracotta", "lamp", "handmade", "diya", "light"],
    materialCost: 250,
    daysOfWork: 2,
    stock: 15,
    status: "Listed",
    image:
      "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=400&q=80&auto=format&fit=crop",
    views: 12,
  },
  {
    id: "cotton-stole-001",
    artisanId: "rajesh-001",
    slug: "handwoven-cotton-stole",
    titleEn: "Handwoven Cotton Stole",
    titleHi: "हाथ बुना हुआ कॉटन स्टोल",
    descriptionEn: "Soft handwoven cotton stole in natural colors",
    descriptionHi: "प्राकृतिक रंगों में मुलायम हाथ से बुना हुआ कॉटन स्टोल",
    keywords: ["cotton", "stole", "handloom", "natural", "wool"],
    materialCost: 400,
    daysOfWork: 3,
    stock: 8,
    status: "Listed",
    image:
      "https://images.unsplash.com/photo-1590732596252-ade07f726197?w=400&q=80&auto=format&fit=crop",
    views: 5,
    lowStock: true,
  },
  {
    id: "chanderi-001",
    artisanId: "rajesh-001",
    slug: "chanderi-dupatta",
    titleEn: "Chanderi Dupatta",
    titleHi: "चंदेरी दुपट्टा",
    descriptionEn: "Pure Chanderi silk dupatta with zari border",
    descriptionHi: "शुद्ध चंदेरी silk दुपट्टा जरी बॉर्डर के साथ",
    keywords: ["chanderi", "silk", "zari", "dupatta", "pure"],
    materialCost: 600,
    daysOfWork: 5,
    stock: 3,
    status: "Draft",
    image:
      "https://images.unsplash.com/photo-1601057374895-01e7d09baa7e?w=400&q=80&auto=format&fit=crop",
    views: 2,
  },
  {
    id: "dhokra-horse-001",
    artisanId: "rajesh-001",
    slug: "dhokra-horse",
    titleEn: "Dhokra Horse",
    titleHi: "धokra घोड़ा",
    descriptionEn: "Lost-wax cast bronze horse figurine",
    descriptionHi: "हारी हुई मोहर से ढाला गया ब्रॉन्ज घोड़ा figurine",
    keywords: ["dhokra", "bronze", "horse", "figurine", "lost-wax"],
    materialCost: 800,
    daysOfWork: 7,
    stock: 1,
    status: "Listed",
    image:
      "https://images.unsplash.com/photo-1614972171036-23d2f8b5e8d8?w=400&q=80&auto=format&fit=crop",
    views: 8,
  },
  {
    id: "bagh-print-001",
    artisanId: "rajesh-001",
    slug: "bagh-bedsheet",
    titleEn: "Bagh Print Bedsheet",
    titleHi: "बाग प्रिंट बिस्तर",
    descriptionEn: "Cotton bedsheet with Bagh block print",
    descriptionHi: "कपास बिस्तर बाग ब्लॉक प्रिंट के साथ",
    keywords: ["bagh", "print", "bedsheet", "cotton", "block"],
    materialCost: 350,
    daysOfWork: 2,
    stock: 12,
    status: "Listed",
    image:
      "https://images.unsplash.com/photo-1622874155148-84aba1e78b6e?w=400&q=80&auto=format&fit=crop",
    views: 18,
  },
  {
    id: "madhubani-001",
    artisanId: "rajesh-001",
    slug: "madhubani-painting",
    titleEn: "Madhubani Painting",
    titleHi: "मधुबानी चित्रकला",
    descriptionEn: "Hand-painted Madhubani art on paper",
    descriptionHi: "कागज पर हाथ से चित्रित मधुबनी कला",
    keywords: ["madhubani", "painting", "hand-painted", "art", "bihar"],
    materialCost: 300,
    daysOfWork: 4,
    stock: 6,
    status: "Listed",
    image:
      "https://images.unsplash.com/photo-1627291299022-88599195fb0e?w=400&q=80&auto=format&fit=crop",
    views: 10,
  },
  {
    id: "blue-pottery-001",
    artisanId: "rajesh-001",
    slug: "blue-pottery-vase",
    titleEn: "Blue Pottery Vase",
    titleHi: "नीला मिट्टी का बर्तन",
    descriptionEn: "Handcrafted blue pottery vase with traditional motifs",
    descriptionHi: "पारम्परिक मोटिफ के साथ हाथ से बनाया गया नीला मिट्टी का बर्तन",
    keywords: ["blue pottery", "vase", "ceramic", "handmade", "motif"],
    materialCost: 450,
    daysOfWork: 3,
    stock: 4,
    status: "Listed",
    image:
      "https://plus.unsplash.com/premium_photo-1663131317299-f46d322a4d35?w=400&q=80&auto=format&fit=crop",
    views: 7,
  },
  {
    id: "channapatna-001",
    artisanId: "rajesh-001",
    slug: "channapatna-toy-set",
    titleEn: "Channapatna Toy Set",
    titleHi: "चन्नपटना खिलौना सेट",
    descriptionEn: "Traditional Channapatna wooden toys",
    descriptionHi: "पारम्परिक चन्नपटना लकड़ी के खिलौने",
    keywords: ["channapatna", "wooden", "toys", "traditional", "karnataka"],
    materialCost: 350,
    daysOfWork: 3,
    stock: 10,
    status: "Listed",
    image:
      "https://images.unsplash.com/photo-1584582262078-682d23623176?w=400&q=80&auto=format&fit=crop",
    views: 6,
  },
  {
    id: "kantha-001",
    artisanId: "rajesh-001",
    slug: "kanthacushion-cover",
    titleEn: "Kantha Cushion Cover",
    titleHi: "कंथा कुशन कवर",
    descriptionEn: "Hand-embroidered Kantha cushion cover",
    descriptionHi: "हाथ से कढ़ाई की हुई कंथा कुशन कवर",
    keywords: ["kantha", "embroidery", "cushion", "cover", "bengal"],
    materialCost: 200,
    daysOfWork: 2,
    stock: 20,
    status: "Listed",
    image:
      "https://images.unsplash.com/photo-1623771881172-fba1a467e80e?w=400&q=80&auto=format&fit=crop",
    views: 9,
  },
  {
    id: "bandhani-001",
    artisanId: "rajesh-001",
    slug: "bandhani-odhani",
    titleEn: "Bandhani Odhani",
    titleHi: "बांधनी ओढ़नी",
    descriptionEn: "Tie-and-dye odhani in vibrant colors",
    descriptionHi: "तीखे रंगों में बांधनी ओढ़नी",
    keywords: ["bandhani", "odhani", "tie-dye", "vibrant", "silk"],
    materialCost: 250,
    daysOfWork: 2,
    stock: 14,
    status: "Listed",
    image:
      "https://images.unsplash.com/photo-1622417591514-334658259d1e?w=400&q=80&auto=format&fit=crop",
    views: 4,
  },
  {
    id: "jute-tote-001",
    artisanId: "rajesh-001",
    slug: "jute-tote-bag",
    titleEn: "Jute Tote Bag",
    titleHi: "जूट टोट बैग",
    descriptionEn: "Eco-friendly jute tote bag",
    descriptionHi: "पूरित्रित जूट टोट बैग",
    keywords: ["jute", "tote", "bag", "eco-friendly", "sustainable"],
    materialCost: 150,
    daysOfWork: 1,
    stock: 25,
    status: "Listed",
    image:
      "https://images.unsplash.com/photo-1557409301-5a5a2f5b9b3e?w=400&q=80&auto=format&fit=crop",
    views: 11,
  },
  {
    id: "brass-diya-001",
    artisanId: "rajesh-001",
    slug: "brass-diya-set",
    titleEn: "Brass Diya Set",
    titleHi: "ब्रास दीया सेट",
    descriptionEn: "Set of 5 brass diyas for puja",
    descriptionHi: "पूजा के लिए 5 ब्रास दीयों का सेट",
    keywords: ["brass", "diya", "puja", "set", "5pcs"],
    materialCost: 300,
    daysOfWork: 3,
    stock: 16,
    status: "Listed",
    image:
      "https://plus.unsplash.com/premium_photo-1663131317299-f46d322a4d35?w=400&q=80&auto=format&fit=crop",
    views: 9,
  },
];

export const ordersSeed = [
  {
    id: "ord-001",
    status: "New",
    amount: 850,
    channel: "Amazon",
    buyerName: "अनिता सिंह",
    buyerPhone: "9876501234",
    timeline: "New → Pack → Ship → Delivered → Paid",
    createdAt: Date.now() - 86400000 * 5,
  },
  {
    id: "ord-002",
    status: "Pack",
    amount: 1200,
    channel: "Flipkart",
    buyerName: "राजेश कुमार",
    buyerPhone: "9876543210",
    timeline: "New → Pack → Ship → Delivered → Paid",
    createdAt: Date.now() - 86400000 * 3,
  },
  {
    id: "ord-003",
    status: "Ship",
    amount: 850,
    channel: "Meesho",
    buyerName: "प्रकाश मिश्रा",
    buyerPhone: "8765432109",
    timeline: "New → Pack → Ship → Delivered → Paid",
    createdAt: Date.now() - 86400000 * 1,
  },
  {
    id: "ord-004",
    status: "Delivered",
    amount: 1200,
    channel: "Amazon",
    buyerName: "साधना देवी",
    buyerPhone: "9123456789",
    timeline: "New → Pack → Ship → Delivered → Paid",
    createdAt: Date.now() - 86400000 * 12,
  },
  {
    id: "ord-005",
    status: "Paid",
    amount: 850,
    channel: "Flipkart",
    buyerName: "विक्रम सिंह",
    buyerPhone: "9234567890",
    timeline: "New → Pack → Ship → Delivered → Paid",
    createdAt: Date.now() - 86400000 * 18,
  },
  {
    id: "ord-006",
    status: "New",
    amount: 600,
    channel: "Meesho",
    buyerName: "सुमन राव",
    buyerPhone: "9345678901",
    timeline: "New → Pack → Ship → Delivered → Paid",
    createdAt: Date.now() - 86400000 * 2,
  },
  {
    id: "ord-007",
    status: "Pack",
    amount: 1500,
    channel: "Amazon",
    buyerName: "कमलेश्वर प्रसाद",
    buyerPhone: "9456789012",
    timeline: "New → Pack → Ship → Delivered → Paid",
    createdAt: Date.now() - 86400000 * 25,
  },
  {
    id: "ord-008",
    status: "Ship",
    amount: 1200,
    channel: "Meesho",
    buyerName: "रूपाली विश्वास",
    buyerPhone: "9567890123",
    timeline: "New → Pack → Ship → Delivered → Paid",
    createdAt: Date.now() - 86400000 * 30,
  },
  {
    id: "ord-009",
    status: "Delivered",
    amount: 850,
    channel: "Amazon",
    buyerName: "सुरेश चंद",
    buyerPhone: "9678901234",
    timeline: "New → Pack → Ship → Delivered → Paid",
    createdAt: Date.now() - 86400000 * 35,
  },
  {
    id: "ord-010",
    status: "Paid",
    amount: 1200,
    channel: "Flipkart",
    buyerName: "प्रवीण कुमार",
    buyerPhone: "9789012345",
    timeline: "New → Pack → Ship → Delivered → Paid",
    createdAt: Date.now() - 86400000 * 42,
  },
  {
    id: "ord-011",
    status: "New",
    amount: 850,
    channel: "Meesho",
    buyerName: "अंजली यादव",
    buyerPhone: "9890123456",
    timeline: "New → Pack → Ship → Delivered → Paid",
    createdAt: Date.now() - 86400000 * 45,
  },
  {
    id: "ord-012",
    status: "Pack",
    amount: 600,
    channel: "Amazon",
    buyerName: "रोहित साहू",
    buyerPhone: "9901234567",
    timeline: "New → Pack → Ship → Delivered → Paid",
    createdAt: Date.now() - 86400000 * 50,
  },
];
